#ifndef FLYINGCAT_CONFIG_H
#define FLYINGCAT_CONFIG_H

#define FLYINGCAT_VERSION "${FLYINGCAT_VERSION}"

#cmakedefine FC_DEBUG_LOG

#cmakedefine HAVE_BACKTRACE
#cmakedefine HAVE_BACKTRACE_SYMBOLS

#endif
